[theme]
primaryColor = "#0c44c7"  
backgroundColor = "#fff6f6"
secondaryBackgroundColor = "#f0f2f6"
font = "sans serif"
textColor = "Black"

[[pages]]
path = "Inicio.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/About_me.py"
name = "About me"
icon = ":books:"

[[pages]]
path = "pages/Asistente.py"
name = "Asistente"
icon = "ğŸˆï¸"

[[pages]]
path = "pages/Brain_tumor_predict.py"
name = "Brain Tumor"
icon = "ğŸˆï¸"
