[[pages]]
path = "Inicio.py"
name = "Inicio"
icon = "ğŸŸ¦ğŸ”µ"

[[pages]]
path = "pages/Asistente.py"
name = "Asistente"
icon = "ğŸ’¬"

[[pages]]
path = "pages/Brain_tumor_predict.py"
name = "Brain Tumor"
icon = "ğŸ§ "

[[pages]]
path = "pages/About_me.py"
name = "About me"
icon = ":books:"
